kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: invoice
  namespace: dc
  selfLink: /apis/build.openshift.io/v1/namespaces/dc/buildconfigs/invoice
  uid: 571ec772-a70b-11e9-8377-0a580a810022
  resourceVersion: '52512124'
  creationTimestamp: '2019-07-15T14:17:55Z'
  labels:
    app: invoice
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'invoice:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:7.2'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/InvoicePlane/InvoicePlane.git'
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:22ba545b450617ca69884a75ab50c421eaf714c2844f0f6882adb97f653d09b5
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 2

