kind: ReplicationController
apiVersion: v1
metadata:
  annotations:
    openshift.io/deployment-config.name: invoice
    openshift.io/deployer-pod.completed-at: '2019-07-15 19:05:27 +0000 UTC'
    openshift.io/deployment.phase: Complete
    openshift.io/deployer-pod.created-at: '2019-07-15 19:04:22 +0000 UTC'
    openshift.io/deployment-config.latest-version: '2'
    openshift.io/deployment.status-reason: image change
    openshift.io/deployment.replicas: ''
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"invoice","namespace":"dc","selfLink":"/apis/apps.openshift.io/v1/namespaces/dc/deploymentconfigs/invoice","uid":"57197296-a70b-11e9-9a71-0a580a82001a","resourceVersion":"52691757","generation":3,"creationTimestamp":"2019-07-15T14:17:55Z","labels":{"app":"invoice"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["invoice"],"from":{"kind":"ImageStreamTag","namespace":"dc","name":"invoice:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/dc/invoice@sha256:9d2d9ccfcd84ddec2f6d5c54f2d50718c524332c418a684cb51dc5ffd86815db"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"invoice","deploymentconfig":"invoice"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"invoice","deploymentconfig":"invoice"}},"spec":{"containers":[{"name":"invoice","image":"image-registry.openshift-image-registry.svc:5000/dc/invoice@sha256:9d2d9ccfcd84ddec2f6d5c54f2d50718c524332c418a684cb51dc5ffd86815db","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"unavailableReplicas":0,"details":{"message":"image
      change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/dc/invoice@sha256:9d2d9ccfcd84ddec2f6d5c54f2d50718c524332c418a684cb51dc5ffd86815db"}}}]},"conditions":[{"type":"Progressing","status":"True","lastUpdateTime":"2019-07-15T14:22:11Z","lastTransitionTime":"2019-07-15T14:22:11Z","reason":"NewReplicationControllerAvailable","message":"replication
      controller \"invoice-1\" successfully rolled
      out"},{"type":"Available","status":"True","lastUpdateTime":"2019-07-15T15:54:20Z","lastTransitionTime":"2019-07-15T15:54:20Z","message":"Deployment
      config has minimum availability."}],"readyReplicas":1}}
    openshift.io/deployer-pod.name: invoice-2-deploy
  selfLink: /api/v1/namespaces/dc/replicationcontrollers/invoice-2
  resourceVersion: '52701848'
  name: invoice-2
  uid: 5ae034bd-a733-11e9-9ca3-0203665c4294
  creationTimestamp: '2019-07-15T19:04:22Z'
  generation: 2
  namespace: dc
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: invoice
      uid: 57197296-a70b-11e9-9a71-0a580a82001a
      controller: true
      blockOwnerDeletion: true
  labels:
    app: invoice
    openshift.io/deployment-config.name: invoice
spec:
  replicas: 1
  selector:
    app: invoice
    deployment: invoice-2
    deploymentconfig: invoice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: invoice
        deployment: invoice-2
        deploymentconfig: invoice
      annotations:
        openshift.io/deployment-config.latest-version: '2'
        openshift.io/deployment-config.name: invoice
        openshift.io/deployment.name: invoice-2
    spec:
      containers:
        - name: invoice
          image: >-
            image-registry.openshift-image-registry.svc:5000/dc/invoice@sha256:9d2d9ccfcd84ddec2f6d5c54f2d50718c524332c418a684cb51dc5ffd86815db
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 2

