kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: invoice
  namespace: dc
  selfLink: /apis/route.openshift.io/v1/namespaces/dc/routes/invoice
  uid: 571eada5-a70b-11e9-8377-0a580a810022
  resourceVersion: '52251830'
  creationTimestamp: '2019-07-15T14:17:55Z'
  labels:
    app: invoice
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: invoice-dc.apps.us-east-2.online-starter.openshift.com
  subdomain: ''
  to:
    kind: Service
    name: invoice
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress:
    - host: invoice-dc.apps.us-east-2.online-starter.openshift.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2019-07-15T14:17:56Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps.us-east-2.online-starter.openshift.com

